<?php
/**
* @file
* This plugin provides functionality to register and connect to your Drupal via IDer Service.
*/

if (!defined('IDER_MODULE_FILE')) {
    define('IDER_MODULE_FILE', __FILE__);
}


if (!defined('IDER_MODULE_DIR')) {
    define('IDER_MODULE_URL', drupal_get_path('module', 'ider_login'));
}

/*
if (!defined('IDER_MODULE_URL')) {
    define('IDER_MODULE_URL', drupal_get_path('module', 'ider_login'));
}
*/

if (!defined('IDER_CLIENT_VERSION')) {
    define('IDER_CLIENT_VERSION', '0.0.1');
}

if (!defined('IDER_SITE_DOMAIN')) {
    define('IDER_SITE_DOMAIN', implode(".", array_reverse(array_slice(array_reverse(explode(".", $_SERVER['HTTP_HOST'])), 0, 2))));
}

if (defined('IDER_SERVER')) {
    \IDERConnect\IDEROpenIDClient::$IDERServer = IDER_SERVER;
}

/**
 * Implements hook_init().
 */
function ider_login_init() {

}

/**
 * Implement hook_help().
 */
function ider_login_help($path, $arg) {
    if($path == 'admin/help#ider_login'){
        $path = $GLOBALS['base_url'] . '/' . drupal_get_path('module', 'gauth');
        $output = '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t("This module allows users to login through the IDer services.") . '</p>';
        $output .= '<h3>' . t('Setup') . '</h3>';
        $output .= '<p>' . t("To setup this module you must fill in the Client ID, the Client Secret and the scope name given by the IDer partner area.") . '</p>';

        return $output;
    }
}

/**
 * Implements hook_menu().
 */
function ider_login_menu() {

    $items = array();

    $items['admin/config/services/ider_login'] = array(
        'title' => 'IDer Login',
        'description' => 'Configure the IDer service to work properly with your site.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ider_login_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

/**
 * Admin form to configure IDer service
 */
function ider_login_form($form, &$form_state) {

    global $base_url;

    $form = array();

    $pluginConfigDescription = '<h1>IDer Single Sign On Configuration</h1>';
    $pluginConfigDescription .= '<p>This plugin is meant to be used with <a target="_blank" href="https://www.ider.com/">IDer Connect System</a></p>';
    $pluginConfigDescription .= '<h5>Setting up IDer Client Account</h5>';
    $pluginConfigDescription .= '<ol>';
    $pluginConfigDescription .= '<li>Create a new client and set the Redirect URI (aka callback URL) to: <strong>' . rtrim($base_url, '/') . '/idercallback</strong></li>';
    $pluginConfigDescription .= '<li>Copy the Client ID and Client Secret in the text fields below.</li>';
    $pluginConfigDescription .= '<li>Set the campaign id to retrieve the user data you chose.</li>';
    $pluginConfigDescription .= '<li>If you open a custom campaign and want your customer to land on a specific page, please configure it in the advanced setting "Campaigns Landing pages" using the format <strong>&lt;Campaign id&gt;=&lt;Landing Page&gt;</strong></li>';
    $pluginConfigDescription .= '<li>You can place the IDer button everywhere using widget, the classic form or the shortcode [ider_login_button]</li>';
    $pluginConfigDescription .= '</ol>';
    $pluginConfigDescription .= '<hr class="description-separator">';

    $form['ider_login_config_description'] = array(
        '#markup' => $pluginConfigDescription,
    );

/*
    $form['#attached']['js'] = array(
        drupal_get_path('module', 'ider_login') . '/assets/js/admin.js',
    );
*/

    $form['#attached']['css'] = array(
        drupal_get_path('module', 'ider_login') . '/assets/css/admin.css',
    );

    $form['ider_login_client_id'] = array(
        '#type' => 'textfield',
        '#title' => t('Client ID'),
        '#default_value' => variable_get('ider_login_client_id'),
        '#required' => TRUE,
        '#element_validate' => array('element_validate_integer')
    );

    $form['ider_login_client_secret'] = array(
        '#type' => 'textfield',
        '#title' => t('Client Secret'),
        '#default_value' => variable_get('ider_login_client_secret'),
        '#required' => TRUE,
    );

    $form['ider_login_scope_name'] = array(
        '#type' => 'textfield',
        '#title' => t('Scope Name'),
        '#default_value' => variable_get('ider_login_scope_name'),
        '#required' => TRUE,
    );

    $form['ider_login_enable_in_login'] = array(
        '#type' => 'checkbox',
        '#title' => t('Add IDer button in the default Drupal login.'),
        '#default_value' => variable_get('ider_login_enable_in_login'),
    );

    $form['ider_login_welcome_page'] = array(
        '#type' => 'textfield',
        '#title' => t('Welcome Page'),
        '#default_value' => variable_get('ider_login_welcome_page'),
        '#required' => FALSE,
        '#field_prefix' => rtrim($base_url, '/') . '/'
    );

    // Also aid in theming of field widgets by rendering a classified container.
    $form['advanced_settings'] = array(
        '#type' => 'fieldset',
        '#title' => t('Advanced Settings'),
        '#description' => t(''),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
    );

    $form['advanced_settings']['ider_login_field_mapping'] = array(
        '#type' => 'textarea',
        '#title' => t('Field Mapping'),
        '#rows' => 6,
        '#default_value' => variable_get('ider_login_field_mapping'),
        '#required' => TRUE,
    );

    $form['advanced_settings']['ider_login_campaigns_landing_pages'] = array(
        '#type' => 'textarea',
        '#title' => t('Campaigns Landing pages'),
        '#rows' => 6,
        '#default_value' => variable_get('ider_login_campaigns_landing_pages'),
        '#required' => FALSE,
    );

    $form['advanced_settings']['ider_login_button_css'] = array(
        '#type' => 'textarea',
        '#title' => t('IDer Button additional css'),
        '#rows' => 6,
        '#default_value' => variable_get('ider_login_button_css'),
        '#required' => FALSE,
    );

    return system_settings_form($form);
}

/**
 * Implements hook_form_alter().
 */
function ider_login_form_alter(&$form, $form_state, $form_id) {
    if ($form_id == 'user_login' || $form_id == 'user_login_block') {
        $form['submit_ider'] = array(
            '#type' => 'submit',
            '#value' => t('Login with IDer'),
            '#attributes'=>array('class' => array('ider-login-button')),
            '#submit' => array('ider_login_auth_submit'),
            '#limit_validation_errors' => array(),
            '#weight' => 1000,
        );
        drupal_add_css(drupal_get_path('module', 'ider_login') . '/assets/css/ider_login.css');
    }
}

function ider_login_auth_submit() {
    // TODO login auth with php
    return 'ciao';
}
